import '@/styles/globals.css';

import { JSX } from 'react';

import type { Metadata } from 'next';

import { cn } from '@/lib/utils';
import { montserrat } from '@/fonts/fonts';
import TanStackProvider from 'src/api/TanStackProvider';
import { ThemeProvider } from '@/components/providers/theme-provider';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Cuồng Phim - Watch Movies Online',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html suppressHydrationWarning lang="en">
      {/* <head /> */}
      <body
        className={cn(
          'tw-themes antialiased scheme-light dark:scheme-dark',
          `${montserrat.className}`,
        )}
      >
        <ThemeProvider
          disableTransitionOnChange
          enableSystem
          attribute="class"
          defaultTheme="system"
        >
          <TanStackProvider>{children}</TanStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
