export const titleLists: string[] = [
  'PHIM BỘ',
  'PHIM LẺ',
  'TV SHOWS',
  'HOẠT HÌNH',
];

export const tabs: string[] = [
  'TRANG CHỦ',
  'PHIM BỘ',
  'PHIM LẺ',
  'TV SHOWS',
  'HOẠT HÌNH',
  'THỂ LOẠI',
  'QUỐC GIA',
];

interface Submenu {
  [key: string]: string[];
}

export const subMenus: Submenu = {
  'QUỐC GIA': [
    'Trung Quốc',
    'Hàn Quốc',
    'Nhật Bản',
    'Thái Lan',
    'Âu Mỹ',
    'Đài Loan',
    'Hồng Kông',
    'Ấn Độ',
    'Anh',
    'Pháp',
    'Canada',
    'Quốc Gia Khác',
    'Đức',
    'Tây Ban Nha',
    'Thổ Nhĩ Kỳ',
    'Hà Lan',
    'Indonesia',
    'Nga',
    'Mexico',
    'Ba lan',
    'Úc',
    'Thụy Điển',
    'Malaysia',
    'Brazil',
    'Philippines',
    'Bồ Đào Nha',
    'Ý',
    'Đan Mạch',
    'UAE',
    'Na Uy',
    'Thụy Sĩ',
    'Châu Phi',
    'Nam Phi',
    'Ukraina',
    'Ả Rập Xê Út',
    'Bỉ',
    'Ireland',
    'Colombia',
    'Phần Lan',
    'Việt Nam',
    'Chile',
    'Hy Lạp',
    'Nigeria',
    'Argentina',
    'Singapore',
  ],
  'THỂ LOẠI': [
    'Hành Động',
    'Tình Cảm',
    'Hài Hước',
    'Cổ Trang',
    'Tâm Lý',
    'Hình Sự',
    'Chiến Tranh',
    'Thể Thao',
    'Võ Thuật',
    'Viễn Tưởng',
    'Phiêu Lưu',
    'Khoa Học',
    'Kinh Dị',
    'Âm Nhạc',
    'Thần Thoại',
    'Tài Liệu',
    'Gia Đình',
    'Chính kịch',
    'Bí ẩn',
    'Học Đường',
    'Kinh Điển',
    'Phim 18+',
  ],
};
