import { nanoid } from 'nanoid';
import { MenuItem } from '@/types/typenavbar';

export const menuItems: MenuItem[] = [
  { id: nanoid(5), category: 'danh-sach', param: 'phim-moi-cap-nhat', label: 'PHIM MỚI', page: 1 },
  { id: nanoid(5), category: 'danh-sach', param: 'phim-bo', label: 'PHIM BỘ', page: 1 },
  { id: nanoid(5), category: 'danh-sach', param: 'phim-le', label: 'PHIM LẺ', page: 1 },
  { id: nanoid(5), category: 'danh-sach', param: 'hoat-hinh', label: 'HOẠT HÌNH', page: 1 },
  { id: nanoid(5), category: 'danh-sach', param: 'tv-shows', label: 'TV SHOWS', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'hanh-dong', label: 'Hành Động', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'tinh-cam', label: 'Tình Cảm', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'hai-huoc', label: 'Hài Hước', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'co-trang', label: 'Cổ Trang', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'tam-ly', label: 'Tâm Lý', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'hinh-su', label: 'Hình Sự', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'chien-tranh', label: 'Chiến Tranh', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'the-thao', label: 'Thể Thao', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'vo-thuat', label: 'Võ Thuật', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'vien-tuong', label: 'Viễn Tưởng', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'phieu-luu', label: 'Phiêu Lưu', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'khoa-hoc', label: 'Khoa Học', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'kinh-di', label: 'Kinh Dị', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'am-nhac', label: 'Âm Nhạc', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'than-thoai', label: 'Thần Thoại', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'tai-lieu', label: 'Tài Liệu', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'gia-dinh', label: 'Gia Đình', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'chinh-kich', label: 'Chính Kịch', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'bi-an', label: 'Bí Ẩn', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'hoc-duong', label: 'Học Đường', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'kinh-dien', label: 'Kinh Điển', page: 1 },
  { id: nanoid(5), category: 'the-loai', param: 'phim-18', label: 'Phim 18+', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'trung-quoc', label: 'Trung Quốc', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'han-quoc', label: 'Hàn Quốc', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'nhat-ban', label: 'Nhật Bản', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'thai-lan', label: 'Thái Lan', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'au-my', label: 'Âu Mỹ', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'dai-loan', label: 'Đài Loan', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'hong-kong', label: 'Hồng Kông', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'an-do', label: 'Ấn Độ', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'anh', label: 'Anh', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'phap', label: 'Pháp', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'canada', label: 'Canada', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'quoc-gia-khac', label: 'Quốc Gia Khác', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'duc', label: 'Đức', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'tay-ban-nha', label: 'Tây Ban Nha', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'tho-nhi-ky', label: 'Thổ Nhĩ Kỳ', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'ha-lan', label: 'Hà Lan', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'indonesia', label: 'Indonesia', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'nga', label: 'Nga', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'mexico', label: 'Mexico', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'ba-lan', label: 'Ba Lan', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'uc', label: 'Úc', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'thuy-dien', label: 'Thụy Điển', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'malaysia', label: 'Malaysia', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'brazil', label: 'Brazil', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'philippines', label: 'Philippines', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'bo-dao-nha', label: 'Bồ Đào Nha', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'y', label: 'Ý', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'dan-mach', label: 'Đan Mạch', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'uae', label: 'UAE', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'na-uy', label: 'Na Uy', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'thuy-si', label: 'Thụy Sĩ', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'chau-phi', label: 'Châu Phi', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'nam-phi', label: 'Nam Phi', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'ukraina', label: 'Ukraina', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'a-rap-xe-ut', label: 'Ả Rập Xê Út', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'bi', label: 'Bỉ', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'ireland', label: 'Ireland', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'colombia', label: 'Colombia', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'phan-lan', label: 'Phần Lan', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'viet-nam', label: 'Việt Nam', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'chile', label: 'Chile', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'hy-lap', label: 'Hy Lạp', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'nigeria', label: 'Nigeria', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'argentina', label: 'Argentina', page: 1 },
  { id: nanoid(5), category: 'quoc-gia', param: 'singapore', label: 'Singapore', page: 1 },
];
